@HostAddress = http://localhost:5043

POST {{HostAddress}}/bug
Accept: application/json
Content-Type: application/application/octet-stream

{
  "title": "Bug",
  "description": "This is the stream body"
}

###
