@issue_65026_HostAddress = http://localhost:5090

# Get the OpenAPI spec - note enum values are in kebab-case
GET {{issue_65026_HostAddress}}/openapi/v1.json
Accept: application/json

###

# This uses kebab-case as documented in the OpenAPI spec - returns 400 (BUG)
GET {{issue_65026_HostAddress}}/enum-value?test=my-value
Accept: application/json

###

# This uses PascalCase which actually works but doesn't match the spec
GET {{issue_65026_HostAddress}}/enum-value?test=MyValue
Accept: application/json

###

# POST with form field using kebab-case as documented in OpenAPI spec - returns 400 (BUG)
POST {{issue_65026_HostAddress}}/enum-form
Content-Type: application/x-www-form-urlencoded

test=my-value

###

# POST with form field using PascalCase - works but doesn't match the spec
POST {{issue_65026_HostAddress}}/enum-form
Content-Type: application/x-www-form-urlencoded

test=MyValue

###

# WORKAROUND: Using JsonParsable<T> wrapper - kebab-case now works
GET {{issue_65026_HostAddress}}/enum-value-workaround?test=my-value
Accept: application/json

###
